# Generated by Django 5.1.5 on 2025-01-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0002_alter_demandeacte_numactedem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeacte',
            name='message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
