# Generated by Django 5.1.5 on 2025-01-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='birthdayPeople',
            field=models.DateField(default=None),
        ),
    ]
