# Generated by Django 5.1.5 on 2025-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_people_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='addressPeople',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='numberPeople',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
